Signup page merge ready
b0llu/Stormpoint-Ecommerce pull request #7
Opened 2022-02-05 09:40 UTC by b0llu

![Uploading image.png…]()

2022-02-12 08:26 UTC, Dev-AkshatGupta commented
This seems great to be merged buddy :)

2022-02-13 09:57 UTC, manojsarna approved these changes
Overall looks good!!

You can merge it!!

2022-02-13 09:57 UTC, manojsarna commented on signup-page/signup.css
> +}
looks good!!

2022-02-13 09:57 UTC, manojsarna commented on signup-page/signup.css
> +    background-color: #d8dcdf;
use rems and px wisely

2022-02-13 09:57 UTC, manojsarna commented on signup-page/signup.css
> +    letter-spacing: 1px;
check to use rems or px

2022-02-13 09:57 UTC, manojsarna commented on signup-page/signup.css
> +        grid-template-areas:
good media queries!!

2022-02-13 09:57 UTC, manojsarna commented on signup-page/signup.css
> +    .margin-left-auto {
good work!!

2022-02-13 09:57 UTC, manojsarna commented on wishlist-page/wishlist.css
> +    border-radius: 50%;
looks great!!

2022-02-13 10:00 UTC, b0llu commented on signup-page/signup.css
> +    letter-spacing: 1px;
fixed

2022-02-13 14:18 UTC, vashnavichauhan1825 requested changes

2022-02-13 14:18 UTC, vashnavichauhan1825 commented on cart-page/cart.css
> +.ammount-container h2 {
spelling correction !

2022-02-13 14:20 UTC, b0llu commented on cart-page/cart.css
> +.ammount-container h2 {
fixed it thanks for pointing it out

2022-02-13 14:21 UTC, merged